apiVersion: apps/v1
kind: Deployment
metadata:
  name: <REPO_NAME>-dp
  labels:
    app.kubernetes.io/instance: <REPO_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: <REPO_NAME>
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: <REPO_NAME>
    spec:
      securityContext: {}
      containers:
        - name: <REPO_NAME>
          securityContext: {}
          image: <IMAGE_NAME>
          imagePullPolicy: IfNotPresent
          
          # ports:

          # envFrom:

          # env:
 
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: '0.3'
              memory: 768Mi
            requests:
              cpu: '0.01'
              memory: 256Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - dev