name: Workflow

on:
  push:
    branches:
      - main
      - 'hotfix**'
      - staging
      - develop
      - 'feature**'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main
      - 'hotfix**'
      - staging
      - develop
      - 'feature**'
    paths-ignore:
      - '**/README.md'

jobs:
    production-test:
        name: 'production-test'
        runs-on: ubuntu-latest
        steps:
          - name: Run a test command
            run: echo test
    staging-test:
        if: github.event_name == 'push' && github.ref == 'refs/heads/staging' ||  github.event_name == 'pull_request' && github.ref == 'refs/heads/staging'
        name: 'staging-test'
        runs-on: ubuntu-latest
        steps:
            - name: Run a test command
              run: echo test
    develop-test:
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop' ||  github.event_name == 'pull_request' && github.ref == 'refs/heads/develop'
        name: 'develop-test'
        runs-on: ubuntu-latest
        steps:
            - name: Run a test command
              run: echo test
    production-build-deploy:
        name: 'production-build-deploy'
        needs: [production-test]
        uses: delvinwang/pomo-action-template/.github/workflows/prod.yml@main
    staging-build-deploy:
        name: 'staging-build-deploy'
        needs: [staging-test]
        uses: delvinwang/pomo-action-template/.github/workflows/stg.yml@main
    develop-build-deploy:
        name: 'develop-build-deploy'
        needs: [develop-test]
        uses: delvinwang/pomo-action-template/.github/workflows/dev.yml@main